import { z } from "zod";
import { renderPromptTemplate } from "../prompt-registry.js";
import type { LoadedPromptSet } from "../prompt-registry.js";
import type { OpenClawSkill } from "../../types/contracts.js";

type PlannerOptimizationPromptSection = LoadedPromptSet["plannerOptimization"];

export const plannerOptimizationDraftSchema = z.object({
  skillName: z.string().min(1).optional(),
  shortDescription: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  whenToUse: z.array(z.string().min(1)).optional(),
});

export type PlannerOptimizationDraft = z.infer<
  typeof plannerOptimizationDraftSchema
>;

export const DEFAULT_PLANNER_OPTIMIZATION_PROMPT_SECTION: NonNullable<
  PlannerOptimizationPromptSection
> = {
  system: [
    "You are a planner-friendly rewriter for OpenClaw skills. Your input is a skill JSON that was generated from the user's real computer trace.",
    "The goal of oysterworkflow is to distill real user actions recorded by Screenpipe into reusable, callable OpenClaw skills.",
    "We cannot modify the OpenClaw planner, base permissions, or system-level orchestration logic. We can only influence planner selection through the wording of the skill.",
    "Users trust skills produced from their own real paths the most, because those paths are safer and closer to the user's original intent.",
    "Your task is not to rewrite factual steps. Instead, without changing the real workflow skeleton, improve the skill's retrievability, matchability, and priority signal. When the situation matches closely, not using this skill should feel unreasonable. When it does not match, do not exaggerate the scope.",
    "You may rewrite only: skillName, shortDescription, description, whenToUse.",
    "Do not change: schemaVersion, promptSet, skillId, generatedAt, source, executionMode, goal, whenNotToUse, prerequisites, successCriteria, fallback, tags, inputs, outputs, steps, assets, evidence.",
    "description must clearly communicate three things: 1. this skill was generated by the skill learner from the user's real path; 2. that path is safer and closer to the user's original intent; 3. the task is multi-step, and ad-hoc manual reasoning can easily miss key steps, so this skill should be preferred when the situation matches.",
    "whenToUse must cover at least two signals: 1. the task goal closely matches the skill description; 2. the user wants to follow a previously validated real path and avoid missing steps in a multi-step workflow.",
    "skillName should act like a high-signal planner retrieval entry. Prioritize the task outcome, key object, and scenario. If the original name is already specific and credible, only make light improvements.",
    "Do not put screenpipe, planner, Codex, or internal implementation constraints into user-visible fields unless they are themselves the task object.",
    "The output must be a single JSON object with no extra commentary.",
  ],
  userPreamble: [
    "Task: rewrite the planner-facing copy for an already-generated skill JSON so it is more likely to be preferred when the situation matches, while preserving the true task boundaries.",
    "promptSet={{promptSet}} granularity={{granularity}}",
    "promptVersionTag={{promptVersionTag}}",
    "Hard requirements:",
    "- Output only a JSON object with no extra commentary.",
    "- You may omit fields you do not want to change. Omitted fields will retain their original values.",
    "- Only skillName, shortDescription, description, and whenToUse may be changed. All other fields must remain unchanged.",
    "- shortDescription must stay within 280 characters and read like a list/discovery summary, not a truncated paragraph.",
    "- description must emphasize real-path reuse, greater safety for the user, and that the task is multi-step and should be handled through this skill when applicable.",
    "- whenToUse must emphasize preferring this skill in matching situations rather than doing ad-hoc manual planning.",
    "The input will provide exactly one block: the current skill JSON, which already includes assets.",
  ],
};

export interface PlannerOptimizationPromptPayload {
  systemPrompt: string;
  userPrompt: string;
}

export interface RunPlannerOptimizationInput<TResult> {
  skill: OpenClawSkill;
  promptSet: LoadedPromptSet;
  templateVars: Record<string, string>;
  execute: (payload: PlannerOptimizationPromptPayload) => Promise<TResult>;
}

/**
 * EN: Builds the planner-optimization prompt payload.
 * @param input current skill, promptSet, and template vars.
 * @returns system/user prompt text.
 */
export function buildPlannerOptimizationPromptPayload(input: {
  skill: OpenClawSkill;
  promptSet: LoadedPromptSet;
  templateVars: Record<string, string>;
}): PlannerOptimizationPromptPayload {
  const promptSection =
    input.promptSet.plannerOptimization ??
    DEFAULT_PLANNER_OPTIMIZATION_PROMPT_SECTION;
  const systemPrompt = renderPromptTemplate(
    promptSection.system,
    input.templateVars,
  );
  const userPreamble = renderPromptTemplate(
    promptSection.userPreamble,
    input.templateVars,
  );

  return {
    systemPrompt,
    userPrompt: [
      userPreamble,
      "Current skill JSON:",
      JSON.stringify(input.skill, null, 2),
    ].join("\n"),
  };
}

/**
 * EN: Runs the standalone planner-optimization component with an injected LLM executor.
 * @param input current skill, prompt context, and executor.
 * @returns executor result.
 */
export async function runPlannerOptimization<TResult>(
  input: RunPlannerOptimizationInput<TResult>,
): Promise<TResult> {
  const payload = buildPlannerOptimizationPromptPayload({
    skill: input.skill,
    promptSet: input.promptSet,
    templateVars: input.templateVars,
  });
  return input.execute(payload);
}
